wx:
  mp:
    configs:
      - appId: wx738d5cd928816fa0
        secret: 4e262bf21fb03bc20a5140ed2a888f5f
        token: hcliu
        aesKey: LHznZTiUOlwohmxktYHFlFQJYnQMeCFPCw8J2QsUHGK
        #aesKey: ENC(XGOwI4PgJuIxTTdqh6SY6xyXVme5ht5alJKAn9LU34qSxhaHfyoBMkLE0elUjcvTYeSd2P/S0Ew=)
server:
  port: 80


notice:
  brakId: VVtPqTFKkTfBFLorEvLDX3

lottery:
  APPID: vinnsglluwk0brol
  APPSECRET: HbKwaYgoIr1DhFFZ9rFoHEHhHZB1bYUT

spring:
  thymeleaf:
    encoding: utf-8

  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/output/
  redis:
    host: 6cbb1cbaf9a8.c.methodot.com
    port: 30667

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
